//gcc dECDSA.c -lgmp -o dECDSA
//echo "F7FD41E28DFCCA32C1CEEF637C202CA6E99E57F18AFEF957DF0866B4CDD60F5C" > hash.txt
//xxd -c 64 -ps -u -r hash.txt test_hash
//xxd -ps -c 64 -u test_hash
//./dECDSA < test_hash | xxd -ps -c 128 -u
//./ecdsa_verify.py 78E0E9DACCC47DE94D674DF3B35624A2F08E600B26B3444077022AD575AF4DB73084B4B8657EEA12396FDE260432BA7BDB3E092D61A42F830150D6CC8D798F9F F7FD41E28DFCCA32C1CEEF637C202CA6E99E57F18AFEF957DF0866B4CDD60F5C 8007ABC1CD96650531BD8039893E8CF549A52D26E2A8A0E4700087523A7156A42794DE699028D0768259367AD4676BFE2DACCA139263A684D0A7434EA3842BC4

#include <Windows.h>
#include <stdio.h>

// Parameters of NIST Curve P-256: y^2 = x^3 + ax + b mod p
//
// underlying field size:
//   p = 2**256 - 2**224 + 2**192 + 2**96 - 1
//     = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
//
// group order (which is prime):
//   n = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551
//
// elliptic curve parameters
//   a = p - 3
//   b = 5ac635d8 aa3a93e7 b3ebbd55 769886bc
//       651d06b0 cc53b0f6 3bce3c3e 27d2604b
//
// base point coordinates:
//   G_x = 6b17d1f2 e12c4247 f8bce6e5 63a440f2
//         77037d81 2deb33a0 f4a13945 d898c296
//   G_y = 4fe342e2 fe1a7f9b 8ee7eb4a 7c0f9e16
//         2bce3357 6b315ece cbb64068 37bf51f5

// Parameters for this reference implementation (generated by keygen.py)
//
// See test_vector for private key and public key
//   d = 0x9C29EDDAEF2C2B4452052B668B83BE6365004278068884FA1AC3F6D0622875C3
//
// public key:
//   Q_x = 0x78E0E9DACCC47DE94D674DF3B35624A2F08E600B26B3444077022AD575AF4DB7,
//   Q_y = 0x42754dfd25c56f939a79f2b204876b3a3ab1ceb2e4ff571abf4fbf36326c8b27

// clang-format off
#pragma warning (disable : 4146)
#include <gmp.h>

// group order and prime modulus
const char* n_str = "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551";
const char* p_str = "ffffffff00000001000000000000000000000000ffffffffffffffffffffffff";

// base point coordinates:
const char* G_x_str = "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296";
const char* G_y_str = "4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5";

// secret key
//const char* d_str = "9C29EDDAEF2C2B4452052B668B83BE6365004278068884FA1AC3F6D0622875C3";
//const char* Q_x_str = "78E0E9DACCC47DE94D674DF3B35624A2F08E600B26B3444077022AD575AF4DB7";
//const char* Q_y_str = "3084B4B8657EEA12396FDE260432BA7BDB3E092D61A42F830150D6CC8D798F9F";

const char* d_str = "84CCCAA904CB397F41A36FF9E05D4EB6C58B8E203E02373C465B6C3F03280C82";
const char* Q_x_str = "DE788A6BECD6FB47AEF1ED68BACDB6866AE05F7389CD6BDF974280BD7FFDED0E";
const char* Q_y_str = "616ABE64FAB6CD780D1AD7803C555651F210C58AAAB0FA767F5BC5C609863A9A";
// clang-format on

/*
AES-128 key:  5D6C69B1247F782670C195845B78BC0F
private key: d = 01E42F4DCFB15884CB8C1681FC1EBBDE9D94F52EA19BCCCE6BE884244CA5BBEA
public key:  Q = (x = 40F8A67E2CC2E5EDF3BE1EEF9BF9EF101D95B0CE7B4972996FAC2AB6003D2110, y = 8AB383312A951935323DBF98BAAD3266F76DF10C454E61E864853DA8C8E95F7D)
encoded public key:  40F8A67E2CC2E5EDF3BE1EEF9BF9EF101D95B0CE7B4972996FAC2AB6003D21108AB383312A951935323DBF98BAAD3266F76DF10C454E61E864853DA8C8E95F7D
88504510604965449685295187971821278471699039696413264168855850291136429273991 20784658592356180313771916637515866430740863717189791274338524166603861693294 104197429850418643457429937468397952002245209053962519060272318418721037198415
Signature: 1AA5AF88E8C8770F9850BF2198FED2AEE2A28320E56D6876578A4F1D8CBA89F3608DB75797F9E8760FEE8BEFF71FF96BF3A19351493BE8D84E0EAB7007445013
*/
typedef struct point {
    mpz_t x, y;
} __Point;
typedef __Point Point[1];

void point_init(Point P) { mpz_inits(P->x, P->y, NULL); }
void point_clear(Point P) { mpz_clears(P->x, P->y, NULL); }

void point_init_set_str(Point        P,
    const char* x_str,
    const char* y_str,
    int          base)
{
    mpz_init_set_str(P->x, x_str, base);
    mpz_init_set_str(P->y, y_str, base);
}

void point_init_infinity(Point P)
{
    mpz_init_set_ui(P->x, 0);
    mpz_init_set_ui(P->y, 0);
}

int point_is_infinity(Point P)
{
    return (mpz_cmp_ui(P->x, 0) == 0) && (mpz_cmp_ui(P->y, 0) == 0);
}

int point_equal(Point P, Point Q)
{
    return (mpz_cmp(P->x, Q->x) == 0) && (mpz_cmp(P->y, Q->y) == 0);
}

int point_is_inverse(Point P, Point Q)
{
    int comp = mpz_cmp(P->x, Q->x) == 0;
    if (comp != 1) {
        return comp;
    }

    // compute negative
    mpz_t Q_y_neg;
    mpz_init(Q_y_neg);
    mpz_neg(Q_y_neg, Q->y);

    comp = mpz_cmp(P->y, Q_y_neg) == 0;
    mpz_clear(Q_y_neg);

    return comp;
}

/* void point_out_str(int base, Point P) */
/* { */
/*   printf("x = "); */
/*   mpz_out_str(stdout, base, P->x); */
/*   printf(", y = "); */
/*   mpz_out_str(stdout, base, P->y); */
/* } */

void point_set(Point R, Point P)
{
    mpz_set(R->x, P->x);
    mpz_set(R->y, P->y);
}

void point_add(Point R, Point P, Point Q, mpz_t a, mpz_t p)
{
    /* assert(R != P && R != Q); */

    if (point_is_infinity(P)) {
        point_set(R, Q);
        return;
    }
    else if (point_is_infinity(Q)) {
        point_set(R, P);
        return;
    }
    if (point_is_inverse(P, Q)) {
        point_init_infinity(R);
        return;
    }

    // lambda
    mpz_t lambda, denominator;
    mpz_inits(lambda, denominator, NULL);
    if (P == Q || point_equal(P, Q)) {
        mpz_powm_ui(lambda, P->x, 2, p);
        mpz_mul_ui(lambda, lambda, 3);
        mpz_add(lambda, lambda, a);

        mpz_mul_ui(denominator, P->y, 2);
        mpz_invert(denominator, denominator, p);
    }
    else {
        mpz_sub(lambda, Q->y, P->y);
        mpz_sub(denominator, Q->x, P->x);
        mpz_invert(denominator, denominator, p);
    }
    mpz_mul(lambda, lambda, denominator);
    mpz_mod(lambda, lambda, p);

    // R->x
    mpz_powm_ui(R->x, lambda, 2, p);

    mpz_sub(R->x, R->x, P->x);
    mpz_sub(R->x, R->x, Q->x);
    mpz_mod(R->x, R->x, p);

    // R->y
    mpz_sub(R->y, P->x, R->x);
    mpz_mul(R->y, lambda, R->y);
    mpz_mod(R->y, R->y, p);
    mpz_sub(R->y, R->y, P->y);
    mpz_mod(R->y, R->y, p);

    // clear mpz
    mpz_clears(lambda, denominator, NULL);
}

void point_scalar(
    Point R, Point P, mpz_t scalar, mp_bitcnt_t num_bits, mpz_t a, mpz_t p)
{
    Point tmp;
    point_init(tmp);

    for (mp_bitcnt_t i = num_bits - 1; i >= 0 && i < num_bits; i--) {
        point_add(tmp, R, R, a, p);

        if (mpz_tstbit(scalar, i) == 1) {
            point_add(R, tmp, P, a, p);
        }
        else {
            point_set(R, tmp);
        }
    }

    point_clear(tmp);
}

void ECDSA_256_sign(unsigned char sig[64], const unsigned char hash[32])
{
    /* parse the group order n */
    mpz_t n;
    mpz_init_set_str(n, n_str, 16);

    /* parse prime p */
    mpz_t p, a;
    mpz_init_set_str(p, p_str, 16);

    mpz_init(a);
    mpz_sub_ui(a, p, 3);

    /* parse base point */
    Point G;
    point_init_set_str(G, G_x_str, G_y_str, 16);

    mpz_t k, r, k_inv;
    mpz_inits(k, r, k_inv, NULL);

    mpz_t z, s, d;
    mpz_inits(z, s, NULL);

    mpz_import(z, 32, 1, 1, 1, 0, hash);
    mpz_set(k, z);  // choose a "random" k

    int loop_counter = 0;
    do {
        /* select a random integer k from [1,n-1]. */
        mpz_add_ui(k, k, loop_counter);
        mpz_mod(k, k, n);
        if (mpz_cmp_ui(k, 0) == 0) {
            loop_counter += 1;
            continue;
        }

        /* calculate the curve point Q = k × G */
        Point Q;
        point_init_infinity(Q);
        point_scalar(Q, G, k, 256, a, p);

        /* calculate r = Q[x] mod n, if r = 0, restart. */
        mpz_mod(r, Q->x, n);
        if (mpz_cmp_ui(Q->x, 0) == 0) {
            loop_counter += 1;
            continue;
        }
        point_clear(Q);

        // calculate s=k^{-1}(z+rd) mod n
        mpz_init_set_str(d, d_str, 16);

        mpz_invert(k_inv, k, n);

        mpz_mul(s, r, d);
        mpz_mod(s, s, n);
        mpz_add(s, s, z);
        mpz_mod(s, s, n);

        mpz_mul(s, s, k_inv);
        mpz_mod(s, s, n);

        /* if s = 0, restart */
        if (mpz_cmp_ui(s, 0) == 0) {
            loop_counter += 1;
            continue;
        }

        break;
    } while (1);

    // export the signature
    mpz_export(sig, NULL, 1, 32, 1, 0, r);
    mpz_export(sig + 32, NULL, 1, 32, 1, 0, s);

    mpz_clears(n, p, a, k, r, z, s, k_inv, d, NULL);
}

int ECDSA_256_check_sig(unsigned char sig[64], const unsigned char hash[32])
{
    int valid = 1;
    /* parse the group order n */
    mpz_t n;
    mpz_init_set_str(n, n_str, 16);

    /* parse prime p */
    mpz_t p, a;
    mpz_init_set_str(p, p_str, 16);

    mpz_init(a);
    mpz_sub_ui(a, p, 3);

    /* parse base point */
    Point G;
    point_init_set_str(G, G_x_str, G_y_str, 16);

    mpz_t z, r, s;
    mpz_inits(z, r, s, NULL);
    mpz_import(z, 32, 1, 1, 1, 0, hash);
    mpz_import(r, 32, 1, 1, 1, 0, sig);
    mpz_import(s, 32, 1, 1, 1, 0, &sig[32]);
    if (mpz_cmp_ui(r, 0) == 0 || mpz_cmp_ui(s, 0) == 0 || mpz_cmp(r, n) >= 0 || mpz_cmp(s, n) >= 0)
        valid = 0;
    mpz_mod(z, z, n);
    gmp_printf("r=%Zx, s=%Zx\n", r, s);
    mpz_t s_inv;
    mpz_init(s_inv);
    mpz_invert(s_inv, s, n);
    mpz_t u1, u2;
    mpz_inits(u1, u2, NULL);
    mpz_mul(u1, z, s_inv);
    mpz_mod(u1, u1, n);
    mpz_mul(u2, r, s_inv);
    mpz_mod(u2, u2, n);
    Point Q;
    point_init_set_str(Q, Q_x_str, Q_y_str, 16);
    Point P1, P2;
    point_init_infinity(P1);
    point_init_infinity(P2);
    point_scalar(P1, G, u1, 256, a, p);
    point_scalar(P2, Q, u2, 256, a, p);
    Point P;
    point_init(P);
    point_add(P, P1, P2, a, p);
    if (point_is_infinity(P)) valid = 0;
    mpz_t chkr;
    mpz_init(chkr);
    mpz_mod(chkr, P->x, n);
    if (mpz_cmp(chkr, r) != 0) valid = 0;
    point_clear(Q);
    point_clear(P1);
    point_clear(P2);
    point_clear(G);
    point_clear(P);
    mpz_clears(n, z, r, s, s_inv, u1, u2, chkr, NULL);
    return valid;
}

extern void vm_ECDSA_256_sign(unsigned char sig[64], const unsigned char hash[32]);

void verify()
{
    unsigned char sig[64];
    unsigned char sigo[64];
    //x = "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
    //", ".join("0x" + x[i*2:(i+1)*2] for i in range(len(x) >> 1))
    unsigned char hash[32] = { 0xF7, 0xFD, 0x41, 0xE2, 0x8D, 0xFC, 0xCA, 0x32, 0xC1, 0xCE, 0xEF, 0x63, 0x7C, 0x20, 0x2C, 0xA6, 0xE9, 0x9E, 0x57, 0xF1, 0x8A, 0xFE, 0xF9, 0x57, 0xDF, 0x08, 0x66, 0xB4, 0xCD, 0xD6, 0x0F, 0x5C };
    unsigned char hash2[32] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    unsigned char hash3[32] = { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF };
    unsigned char hash4[32] = { 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xBC, 0xE6, 0xFA, 0xAD, 0xA7, 0x17, 0x9E, 0x84, 0xF3, 0xB9, 0xCA, 0xC2, 0xFC, 0x63, 0x25, 0x51 };
    unsigned char hash5[32];
    ECDSA_256_sign(sig, hash);
    vm_ECDSA_256_sign(sigo, hash);
    printf("%d %d\n", ECDSA_256_check_sig(sig, hash), ECDSA_256_check_sig(sigo, hash));
    ECDSA_256_sign(sig, hash2);
    vm_ECDSA_256_sign(sigo, hash2);
    printf("%d %d\n", ECDSA_256_check_sig(sig, hash2), ECDSA_256_check_sig(sigo, hash2));
    ECDSA_256_sign(sig, hash3);
    vm_ECDSA_256_sign(sigo, hash3);
    printf("%d %d\n", ECDSA_256_check_sig(sig, hash3), ECDSA_256_check_sig(sigo, hash3));
    ECDSA_256_sign(sig, hash4);
    vm_ECDSA_256_sign(sigo, hash4);
    printf("%d %d\n", ECDSA_256_check_sig(sig, hash4), ECDSA_256_check_sig(sigo, hash4));
    gmp_randstate_t grst;
    gmp_randinit_default(grst);
    mpz_t num;
    mpz_init(num);
    for (int i = 0; i < 6; i++) {
        mpz_urandomb(num, grst, 256);
        mpz_export(hash5, NULL, 1, 32, 1, 0, num);
        ECDSA_256_sign(sig, hash5);
        vm_ECDSA_256_sign(sigo, hash5);
        int chk1 = ECDSA_256_check_sig(sig, hash5);
        int chk2 = ECDSA_256_check_sig(sigo, hash5);
        if (!chk1 || !chk2) break;
        printf("%d %d\n", chk1, chk2);
    }
    mpz_clear(num);
}

void timing()
{
    unsigned char sig[64];
    unsigned char hash[32] = { 0xF7, 0xFD, 0x41, 0xE2, 0x8D, 0xFC, 0xCA, 0x32, 0xC1, 0xCE, 0xEF, 0x63, 0x7C, 0x20, 0x2C, 0xA6, 0xE9, 0x9E, 0x57, 0xF1, 0x8A, 0xFE, 0xF9, 0x57, 0xDF, 0x08, 0x66, 0xB4, 0xCD, 0xD6, 0x0F, 0x5C };
    LARGE_INTEGER start;
    LARGE_INTEGER stop;
    LARGE_INTEGER frequency;
    QueryPerformanceFrequency(&frequency);
    QueryPerformanceCounter(&start);
    for (int i = 0; i < 10; i++)
        ECDSA_256_sign(sig, hash);
    QueryPerformanceCounter(&stop);
    printf("GMP ECDSA p256: %lf seconds\n", (double)(stop.QuadPart - start.QuadPart) / (double)frequency.QuadPart);
    QueryPerformanceCounter(&start);
    for (int i = 0; i < 10; i++)
        vm_ECDSA_256_sign(sig, hash);
    QueryPerformanceCounter(&stop);
    printf("Graph ECDSA p256: %lf seconds\n", (double)(stop.QuadPart - start.QuadPart) / (double)frequency.QuadPart);
}

void test()
{
    verify();
    timing();
}

int main()
{
    test();
    unsigned char sig[64];
    unsigned char hash[32];

    while (!feof(stdin)) {
        int l = fread(hash, 32, 1, stdin);
        if (l != 1) break;

        ECDSA_256_sign(sig, hash);

        l = fwrite(sig, 64, 1, stdout);
        if (l != 1) break;
    }
    return 0;
}